### ISSUE TITLE
List of Issues

### ISSUE THREAD

**Issue by alikoyakp** [consoleerp/ctechnology_erpnext#2]
Control Technology Requirements 22-03-2017
------------------------------------------
- [x] Quotation --> Need to show available qty in all warehouse in detail for item
- [x] Quotation --> Disc% same as in Sales Invoice and show price after discount
- [x] Quotation --> Need one column in header to write Notes
- [x] Quotation --> Need one column in detail "Availability" and the values should come
		automatically and can be editable
		a. if qty is available , show "Available"
		b. if qty not available, show "Not Available"
		c. if qty is 10 and available is 3, show "3 available 7 not available"
- [x] Quotation --> Terms Should be mandatory

- [x] Sales Invoice --> Salesman by Territory and should be mandatory
- [x] Sales Invoice --> Need to see "profit" of the "total invoice" some where in the screen
- [x] Customer --> Add one column "Is Pos" and if ticked, it should reflect in the sales invoice

**Comment by fahimalizain** [comment]
there is no `Sales Man`, only `Sales Team`. Proceed ?
